export const AUTH_LOADING = "AUTH_LOADING";

export const AUTH_ERROR = "AUTH_ERROR";

export const AUTH_LOGGED_IN = "AUTH_LOGGED_IN";

export const AUTH_RESET_ERROR = "AUTH_RESET_ERROR";

export const AUTH_USER_REGISTERED = "AUTH_USER_REGISTERED";

export const AUTH_RESET_USER_REGISTERED = "AUTH_RESET_USER_REGISTERED";

export const CANDIDATE_LOADING = "CANDIDATE_LOADING";

export const CANDIDATE_ERROR = "CANDIDATE_ERROR";

export const CANDIDATE_RESET_ERROR = "CANDIDATE_RESET_ERROR";

export const CANDIDATE_INVITATION_FETCHED = "CANDIDATE_INVITATION_FETCHED";

export const CANDIDATE_JOBS_FETCHED = "CANDIDATE_JOBS_FETCHED";

export const CANDIDATE_SAVED_JOBS_FETCHED = "CANDIDATE_SAVED_JOBS_FETCHED";

export const AUTH_PROFILE_FETCHED = "AUTH_PROFILE_FETCHED";

export const CANDIDATE_EDUCATION_ADDED = "CANDIDATE_EDUCATION_ADDED";

export const CANDIDATE_JOB_ADDED = "CANDIDATE_JOB_ADDED";

export const EMPLOYER_LOADING = "EMPLOYER_LOADING";

export const EMPLOYER_ERROR = "EMPLOYER_ERROR";

export const EMPLOYER_RESET_ERROR = "EMPLOYER_RESET_ERROR";

export const EMPLOYER_CANDIDATES_FETCHED = "EMPLOYER_CANDIDATES_FETCHED";

export const EMPLOYER_JOBS_FETCHED = "EMPLOYER_JOBS_FETCHED";

export const EMPLOYER_FAVORITES_FETCHED = "EMPLOYER_FAVORITES_FETCHED";

export const EMPLOYER_CANDIDATE_PROFILE_FETCHED = "EMPLOYER_CANDIDATE_PROFILE_FETCHED";

export const EMPLOYER_SET_CANDIDATE_ID = "EMPLOYER_SET_CANDIDATE_ID";

export const EMPLOYER_JOB_CREATED = "EMPLOYER_JOB_CREATED";

export const EMPLOYER_HIRED_CANDIDATES_FETCHED = "EMPLOYER_HIRED_CANDIDATES_FETCHED";

export const AUTH_RESET_LOGIN = "AUTH_RESET_LOGIN";

export const AUTH_PASSWORD_CHANGED = "AUTH_PASSWORD_CHANGED";

export const CANDIDATE_SELECT_JOB = "CANDIDATE_SELECT_JOB";

export const CANDIDATE_APPLY_JOB_FILTER = "CANDIDATE_APPLY_JOB_FILTER";

export const EMPLOYER_APPLIED_CANDIDATES_FETCHED = "EMPLOYER_APPLIED_CANDIDATES_FETCHED";

export const EMPLOYER_APPLY_CANDIDATE_FILTER = "EMPLOYER_APPLY_CANDIDATE_FILTER";