export const AUTH_LOADING = "AUTH_LOADING";

export const AUTH_ERROR = "AUTH_ERROR";

export const AUTH_LOGGED_IN = "AUTH_LOGGED_IN";

export const AUTH_RESET_ERROR = "AUTH_RESET_ERROR";

export const AUTH_USER_REGISTERED = "AUTH_USER_REGISTERED";

export const AUTH_RESET_USER_REGISTERED = "AUTH_RESET_USER_REGISTERED";

export const CANDIDATE_LOADING = "CANDIDATE_LOADING";

export const CANDIDATE_ERROR = "CANDIDATE_ERROR";

export const CANDIDATE_RESET_ERROR = "CANDIDATE_RESET_ERROR";

export const CANDIDATE_INVITATION_FETCHED = "CANDIDATE_INVITATION_FETCHED";

export const CANDIDATE_JOBS_FETCHED = "CANDIDATE_JOBS_FETCHED";

export const CANDIDATE_SAVED_JOBS_FETCHED = "CANDIDATE_SAVED_JOBS_FETCHED";

export const AUTH_PROFILE_FETCHED = "AUTH_PROFILE_FETCHED";